config/routes.rb
Rails.application.routes.draw do
  resources :items

  devise_for :users
  devise_for :models
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all
    can :manage, Item do |item|
        item.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged

	belongs_to :user
	has_many :sales
	has_attached_file :image
	has_attached_file :resource

	validates_attachment_content_type :image, 
	content_type:  /^image\/(png|gif|jpeg)/,
	message: "Sólo las imágenes permitidas"
	 
	validates_attachment_content_type :resource,
	content_type: ['application/pdf'],
	message: "Sólo pdfs permite"
	 
	validates :image, attachment_presence: true
	validates :resource, attachment_presence: true

	validates_numericality_of :price,
	greate_than: 49, message: "Debe tener al menos 50 centavos"
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	before_create :populate_guid
	belongs_to :item

	include AASM 

	aasm column: 'state' do
		state :pending, initial: true
		state :processing
		state :finished
		state :errored

		event :process, after: :charge_card do
			transitions from: :pending , to: :processing 
		end
	
		event :finish do
			transitions from: :processing, to: :finished
		end

		event :fail do
			transitions from: :processing, to: :errored
		end
	end

	def charge_card
		begin
			save!
			charge = Stripe::Charge.create(
				amount: self.amount,
				currency: "eur",
				card: self.stripe_token,
				description: "Item sale"
				)
			self.update(stripe_id: charge.id)
			self.finish!
		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!
		end
	end
	
	private

	def populate_guid
		self.guid = SecureRandom.uuid()
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_path, notice: "No tiene permisos para acceder a este área."
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :edit, :create, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(availability: true)
    respond_with(@item)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_with(@item)
  end

  # GET /items/new
  def new
    @item = Item.new
    respond_with(@item)
  end

  # GET /items/1/edit
  def edit
    authorize! :manage, @item
  end

  def create
    @item = current_user.items.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    authorize! :manage, @item
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    authorize! :manage, @item
    @item.destroy
    respond_with(@item)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :seller, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_action :authenticate_user!, only: [:dashboard]

  def home
  	if current_user
  		redirect_to items_path
  	end
  	@items = Item.last(4)
  end

  def dashboard
  	@items = current_user.items
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def create
		item = Item.find_by!(slug: params[:slug])
		sale = item.sales.create(
			amount: item.price,
			buyer_email: current_user.email,
			seller_email: item.user.email,
			stripe_token: params[:stripeToken])
		sale.process!
		if sale.finished?
			redirect_to pickup_url(guid: sale.guid), notice: "Transacción exitosa"
		else
			redirect_to item_path(item), notice: "Algo salió mal"
		end
	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@item = @sale.item
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, required: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
    <%= f.input :seller, required: true, label: false, placeholder: "Nombre del fabricante", input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Descripción del Producto", input_html: {class: "form-control"} %>
    <%= f.input :price, required: true, label: false, placeholder: "Precio", input_html: {class: "form-control"} %>
    
    <%= f.input :image %>
    <%= f.input :resource %>
	<div class="checkbox text-center">
    <p>Disponibilidad</p>
    	<%= f.input :availability, required: false, label: false %>
	</div>

    <%if @item.id %>
        <%= f.button :submit, "Editar producto", class: "btn btn-success btn-block" %>
    <% else %>
        <%= f.button :submit, "Crear producto", class: "btn btn-success btn-block" %>
    <% end %>
<% end %>

app/views/items/_item.html.erb
<div class="col-md-3">
  <div class="thumbnail">
  	<%= link_to item_path(item) do %>
    	<%= image_tag item.image.url(:original), class: "img-responsive"%>
  	<% end %>
  <div class="caption">
    <p><strong><%= link_to item.name, item_path(item), class: 'link_custom' %></strong></p>
    <p><%= item.price.to_f / 100 %> €</p>
  </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1 class="text-center">Editar producto</h1>

<%= render 'form' %>
<div class="text-center">
<%= link_to 'Atrás', items_path, class: "link_custom" %>
</div>

app/views/items/index.html.erb
<div class="row">

<%= render @items %>

</div>

app/views/items/new.html.erb
<h1 class="text-center">Nuevo producto</h1>

<%= render 'form' %>
<div class="text-center">
<%= link_to 'Atrás', items_path, class: "link_custom" %>
</div>

app/views/items/show.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6">
    <%= image_tag @item.image.url(:original), class: "img-responsive" %>
  </div>
  <div class="col-md-6">
    <h3 class><%= @item.name %> - <%= @item.seller %> </h3>
    <p class="justify"><%= @item.description %> </p>
    <h4 class="text-right"><%= @item.price.to_f / 100 %>€</h4>

    <% if current_user %>
      <%= form_tag buy_path(slug: @item.slug) do %>
  	    <script
  		    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  		    data-key="<%= Rails.configuration.stripe[:publishable_key]%>"
  		    data-amount="<%= @item.price %>"
  		    data-name="Organico"
  		    data-description="<%= @item.name %>"
  		    data-email="<%= current_user.email %>">
  	    </script>
      <% end %>
    <% else %>
      <p>Por favor, primero regístrese para comprar</p>
    <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-certificate'></i><big> orgánico</big>".html_safe, root_path, {:style=>'color:#FFFFFF;', :class => "navbar-brand"}%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "PRODUCTOS ORGÁNICOS".upcase, items_path,{:style=>'color:#FFFFFF;'} %></li>  
      
      <% if current_user %>  
        <li><%= link_to "Ajustes".upcase, edit_user_registration_path, {:style=>'color:#FFFFFF;'} %></li>
        <li><%= link_to "DASHBOARD".upcase, dashboard_path, {:style=>'color:#FFFFFF;'} %></li>
        <li><%= link_to "CERRAR SESIÓN".upcase, destroy_user_session_path, {:style=>'color:#FFFFFF;', :method=> :delete} %></li>
      <% else %>
        <li><%= link_to "Iniciar SESIÓN".upcase, new_user_session_path, {:style=>'color:#FFFFFF;'} %></li>
      <% end %>
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>orgánico</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">  
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>
<body>

<%= render "layouts/header"%>
	<% flash.each do |type, message| %>
		<div class="alert alert-info fade-in">
			<button class="close" data-dismiss="alert">x</button>
			<%= message %>
		</div>
	<% end %>
	<%= yield %>
</body>
</html>

app/views/pages/_items.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Disponible</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, item_path(item), class: "link_custom" %></td>
      <td><%= item.availability %></td>
      <td><%= link_to "Editar", edit_item_path(item), class: "link_custom" %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/pages/_purchased.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @purchased.each do |sale| %>
    <tr>
      <td><%= link_to sale.item.name, pickup_path(sale.guid), class: "link_custom" %></td>
      <td><%= time_ago_in_words(sale.created_at) %> ago</td>  
    </tr>
	<% end %>
</tbody>
</table>

app/views/pages/_sales.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th>Comprador</th>
    </tr>
  </thead>
  <tbody>
  <% @purchased.each do |sale| %>
    <tr>
      <td><%= link_to sale.item.name, pickup_path(sale.guid), class: "link_custom" %></td>
      <td><%= time_ago_in_words(sale.created_at) %> ago</td>  
      <td><%= sale.buyer_email %> ago</td>  
    </tr>
	<% end %>
</tbody>
</table>

app/views/pages/dashboard.html.erb
<h1 class="center_subheader">Dashboard</h1>
<br>
<div class="text-center">
	<%= link_to "Nuevo producto", new_item_path, class: "btn btn-success btn-sm" %>
</div>

<div class="col-md-4">
<div class="dash-box">
<h4 class="white-uppercase">
Productos
</h4>
</div>
<%= render "items"%>
</div>

<div class="col-md-4">
<div class="dash-box">
<h4 class="white-uppercase">
Compras
</h4>
</div>
<%= render "purchased"%>
</div>

<div class="col-md-4">
<div class="dash-box">
<h4 class="white-uppercase">
Ventas
</h4>
</div>
<%= render "sales"%>
</div>

app/views/pages/home.html.erb
<div class="home-background">

  <div class="container">
    <div class="col-lg-8 col-lg-offset-2">
      
      <div class="jumbotron text-center">
        <h2>DEL CAMPO A TU MESA</h2>
        <p>Comida orgánica a dormicillio</p>
        <%= link_to "PRODUCTOS ORGÁNICOS", items_path, class: "btn btn-success btn-block"%>
        <%= link_to "REGÍSTRATE", new_user_registration_path, class: "btn btn-success btn-block"%>
      </div>

    </div>

    <div class="row">
      <%= render @items %>
    </div>

  </div>

</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
	<h1>Felicitaciones por tu pedido <%= @sale.guid %></h1>
	<p>Aquí está tu confirmación de la orden:</p>
	<%= link_to "Descargar", @item.resource.url %>
</div>